import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import Head from 'next/head';

interface FAQItem {
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    question: 'What types of leads does NAASS generate?',
    answer:
      'NAASS specialises in five core lead types: ECO 4 scheme leads for energy efficiency installers, housing disrepair leads for claims management companies and solicitors, life insurance leads for brokers and advisers, and enquiries generated through our Google PPC and social media advertising management services. Each lead type is generated through dedicated campaigns tailored to the specific audience and qualification criteria of that market.',
  },
  {
    question: 'How does your lead generation process work?',
    answer:
      'We run targeted digital campaigns across Google Search, Facebook, Instagram, and other platforms to reach individuals who are actively seeking the services you offer. Every prospect completes a multi-step qualification process — capturing key eligibility or intent data — before the lead is delivered to your team in real time. This ensures the people you speak with have a genuine, verified interest and meet the criteria you care about most.',
  },
  {
    question: 'What is ECO 4 and how can I get ECO 4 leads?',
    answer:
      'ECO 4 is the UK government\'s Energy Company Obligation scheme, which funds free or subsidised home energy improvements — including insulation, boiler upgrades, and heat pump installations — for low-income and fuel-poor households. To receive ECO 4 leads from NAASS, simply get in touch via our enquiry form. We will assess your coverage area, agree on qualification criteria, and begin delivering verified, pre-screened leads directly to your CRM or inbox.',
  },
  {
    question: 'How quickly will I receive leads after signing up?',
    answer:
      'For most clients, campaigns are live and delivering their first leads within 3 to 5 working days of onboarding. The setup process involves agreeing qualification criteria, configuring your lead delivery method (email, webhook, or CRM integration), and launching your dedicated campaigns. Once live, leads are delivered in real time — typically within minutes of a prospect completing the qualification journey.',
  },
  {
    question: 'What makes your leads different from other providers?',
    answer:
      'NAASS generates every lead fresh through our own campaigns — we do not purchase aged data, scrape databases, or recycle old enquiries. Each lead carries a verified GDPR consent record captured at the point of enquiry, and our multi-stage qualification process filters out tyre-kickers before the lead reaches your team. The result is a consistently higher conversion rate compared with leads purchased from aggregators or data brokers.',
  },
  {
    question: 'Do you offer exclusive leads?',
    answer:
      'Yes. All leads generated by NAASS are delivered exclusively to a single client and are never shared with or sold to competitors. We believe that exclusivity is fundamental to a healthy conversion rate and a trustworthy long-term partnership. If you have volume requirements that benefit from a non-exclusive arrangement, we can discuss that on a case-by-case basis, but exclusivity is our default and recommended option.',
  },
  {
    question: 'What areas of the UK do you cover?',
    answer:
      'NAASS operates nationally across England, Scotland, and Wales. Our campaigns can be configured to target specific regions, counties, or postcodes if your business serves a defined geographic area, or set to cover the whole of the UK if you operate nationally. We work with clients ranging from local sole traders to national companies, and our targeting is flexible enough to accommodate either.',
  },
  {
    question: 'How much do your lead generation services cost?',
    answer:
      'Pricing varies depending on the lead type, volume, and level of qualification required. We offer competitive per-lead pricing with no long-term lock-in contracts, as well as managed service packages for clients who want us to handle their entire digital advertising strategy. The best way to get accurate pricing is to request a free quote — we will put together a bespoke proposal based on your specific requirements.',
  },
  {
    question: 'Can I choose which types of leads I receive?',
    answer:
      'Absolutely. You choose the lead types, qualification criteria, geographic coverage, and volume that work for your business. You can also set caps on daily or weekly lead volumes to ensure your team can follow up effectively without being overwhelmed. Our account management team works with you on an ongoing basis to adjust parameters as your business needs evolve.',
  },
  {
    question: 'What is your lead replacement policy?',
    answer:
      'We stand behind the quality of every lead we deliver. If a lead is found to be invalid — for example, the contact details are incorrect, the prospect is unreachable after reasonable attempts, or they significantly misrepresented their circumstances during the qualification process — we will replace it at no additional charge. Our replacement process is straightforward and handled quickly, typically within one working day of a valid replacement request.',
  },
];

const FAQ: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((faq) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: faq.answer,
      },
    })),
  };

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <>
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        />
      </Head>
      <section className="py-20 bg-white" id="faq">
        <div className="container mx-auto px-4">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-orange-500 mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-gray-600 max-w-2xl mx-auto text-lg">
              Everything you need to know about our lead generation services. Can't find the answer you're looking for?{' '}
              <a href="#contact" className="text-orange-500 underline hover:text-orange-600 transition-colors">
                Get in touch.
              </a>
            </p>
          </motion.div>

          <div className="max-w-3xl mx-auto space-y-3">
            {faqs.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: index * 0.05 }}
                className="border border-gray-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow"
              >
                <button
                  onClick={() => toggle(index)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 bg-white hover:bg-orange-50 transition-colors"
                  aria-expanded={openIndex === index}
                >
                  <span className="font-semibold text-orange-500 pr-4 text-base leading-snug">
                    {faq.question}
                  </span>
                  <motion.span
                    animate={{ rotate: openIndex === index ? 180 : 0 }}
                    transition={{ duration: 0.25 }}
                    className="flex-shrink-0 text-orange-500"
                  >
                    <ChevronDown className="w-5 h-5" />
                  </motion.span>
                </button>

                <AnimatePresence initial={false}>
                  {openIndex === index && (
                    <motion.div
                      key="answer"
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: 'easeInOut' }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-5 pt-2 bg-white border-t border-gray-100">
                        <p className="text-gray-600 leading-relaxed text-sm">{faq.answer}</p>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>
        </div>
      </section>
    </>
  );
};

export default FAQ;
